### ISSUE TITLE
Product Tracking

### ISSUE THREAD

**Issue by RevoLand** [RevoLand/node-amazon-tracker#4]
- [x] Parsing ASIN from URL
- [x] Parsing product details
- [x] Support for rest of the Amazon websites (com, uk, de, es, fr, it)
- [x] Settings
- [x] Auto tracking existing products
- [x] Tracking optimizations
